{
 "title": "Weather Station Dashboard",
 "time": { "from": "2019-05-20T22:00:00.000Z", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Temperature & Humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time_measured,$__interval),\n  temperature AS \"Temperature [°C]\",\n  humidity AS \"Humidity [g/m³]\",\n  relative_humidity AS \"Relative Humidity [%H]\"\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY $__unixEpochGroup(time_measured,$__interval)"
    }
   ]
  },
  {
   "title": "Information about graphing tool",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "content": "Press ESC to change the selected time span in the upper right-hand corner.",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  station_id\nFROM measurements\nWHERE\n  $__timeFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Information about measurement interval",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "content": "A connected weather station sends a measurement every 5 seconds from the beginning.",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  station_id\nFROM measurements\nWHERE\n  $__timeFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Last measurement:",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\"\nFROM measurements\nORDER BY time_measured DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Last Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Last Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Last Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  relative_humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\"\nFROM measurements\nORDER BY time_measured DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Measurements in the selected time range (to be seen above)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM measurements\nWHERE $__unixEpochFilter(time_measured)"
    }
   ]
  },
  {
   "title": "Total recorded measurements",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM measurements;"
    }
   ]
  },
  {
   "title": "Maximum Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "format": "celsius",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Maximum Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "format": "congm3",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Maximum Relative Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "format": "humidity",
   "valueName": "max",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  relative_humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "format": "congm3",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Average Relative Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  relative_humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Minimum Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "format": "celsius",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Minimum Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "format": "congm3",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Minimum Relative Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "format": "humidity",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  relative_humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature,\n  humidity,\n  relative_humidity,\n  station_id,\n  id\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Temperature Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  temperature\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Humidity Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  },
  {
   "title": "Relative Humidity Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_measured AS \"time\",\n  relative_humidity\nFROM measurements\nWHERE\n  $__unixEpochFilter(time_measured)\nORDER BY time_measured"
    }
   ]
  }
 ]
}